config/routes.rb
GrouperApp::Application.routes.draw do

  resources :events

  resources :locations
  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place
  attr_accessible :description, :end, :name, :start, :other, :date, :place_id
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :event_name, :start_time, :end_time, :address, :latitude, :longitude, :description
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :events
  attr_accessible :description, :latitude, :longitude, :name, :string
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Event.where("end>?", DateTime.now).near(params[:search], 0.75, :order => 'start_time, distance')
    else
      @locations = Event.where("end>?", DateTime.now).order(:start)
    end
  end

  def show
    @location = Event.find(params[:id])
  end

  def new
    @location = Event.new
  end

  def create
    @location = Event.new(params[:location])
    if @location.save
      redirect_to @location, :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Event.find(params[:id])
  end

  def update
    @location = Event.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, :notice  => "Successfully updated event."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Event.find(params[:id])
    @location.destroy
    redirect_to locations_url, :notice => "Successfully destroyed event."
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      @locations = Location.where("end_time>?", DateTime.now).near(params[:search], 0.75, :order => 'start_time, distance')
    else
      @locations = Location.where("end_time>?", DateTime.now).order(:start_time)
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to @location, :notice => "Successfully created event."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, :notice  => "Successfully updated event."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_url, :notice => "Successfully destroyed event."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<head>
  <link rel="stylesheet" href="application.css">
</head>

<h1>
  <font face="century gothic, palatino, arial">
    <font size="48">
      <u>Talk Grouper</u>
      <%= image_tag("grouper.png", :alt => "nil") %>
    </font size>
  </font face>
</h1>



<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Events Near You", :name => nil %>
  </p>
<% end %>

<table>
  <% for location in @locations %>
    <tr>
      <td>
        <font size="5">
          <font face="century gothic, palatino, arial">
            <strong>
            <%= link_to location.name, location %>
            </strong>
          </font face>
        </font size>
      </td>
    </tr>
    <tr>
      <td><%= location.start.strftime("%I:%M%p") + " - " + location.end.strftime("%I:%M%p") %></td>
    </tr>
    <tr>
      <td>
        <% if location.place%>
        <%= location.place.name %>
        <%end%>
      </td>
    </tr>
    <tr>
      <td><%= link_to "Show", location %> <%= link_to "Edit", edit_location_path(location) %> <%= button_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Event", new_location_path %></p>

<footer>
  <font size="3">
      (Has no official affiliation to MIT Admissions)
  </font size>
</footer>


<script>
var s = document.getElementById("search");
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }
function showPosition(position)
  {
  s.value = position.coords.latitude + "," + position.coords.longitude;
  }
    getLocation();
</script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Start:</b>
  <%= @event.start %>
</p>

<p>
  <b>End:</b>
  <%= @event.end %>
</p>

<p>
  <b>Place:</b>
  <%= @event.place %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :event_name %><br />
    <%= f.text_field :event_name %>
    *
  </p>
  <p>
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
    *
  </p>
  <p>
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
    *
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
    *
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<% title "Edit Location" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<head>
  <link rel="stylesheet" href="application.css">
</head>

<h1> 
  <font face="century gothic, palatino, arial"> 
    <font size="48"> 
      <u>Talk Grouper</u>
      <%= image_tag("grouper.png", :alt => "nil") %> 
    </font size>
  </font face>
</h1>

<h2>
  <font face="century gothic, palatino, arial">
    <%= image_tag("MIT_CPW.jpg", :alt => "nil") %> Events Close To You
  </font face>
</h2>

<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Events Near You", :name => nil %>
  </p>
<% end %>

<table>
  <% for location in @locations %>
    <tr>
      <td>
        <font size="5">
          <font face="century gothic, palatino, arial">
            <strong>
            <%= link_to location.event_name, location %>
            </strong>
          </font face>
        </font size>
      </td>
    </tr>
    <tr>
      <td><%= location.start_time.ctime() + " - " + location.end_time.ctime() %></td>
    </tr>
    <tr>
      <td>
        <%= location.address %>
      </td>
    </tr>
      <td><%= link_to "Show", location %> <%= link_to "Edit", edit_location_path(location) %> <%= button_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Event", new_location_path %></p>

<footer>
  <font size="3">
      (Has no official affiliation to MIT Admissions) 
  </font size>
</footer>



<script>
var s = document.getElementById("search");
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }
function showPosition(position)
  {
  s.value = position.coords.latitude + "," + position.coords.longitude;
  }
    getLocation();
</script>

app/views/locations/new.html.erb
<% title "New Event" %>

<%= render 'form' %>

<p><%= link_to "Back to Nearby Events", locations_path %></p>

app/views/locations/show.html.erb
<h1> 
  <font face="century gothic, palatino, arial"> 
    <font size="48"> 
      <u>Talk Grouper</u>
      <%= image_tag("grouper.png", :alt => "nil") %> 
    </font size>
  </font face>
</h1>

<h3>
    <font size="6">
      <font face="century gothic, palatino, arial"> 
        <%= @location.event_name %>
      </font face>
    </font size>
</h3>
<p>
  <strong>Start Time:</strong>
  <%= @location.start_time.ctime() %>
</p>
<p>
  <strong>End Time:</strong>
  <%= @location.end_time.ctime() %>
</p>
<p>
  <%= @location.address %>
</p>
<p>
  <%= @location.description %>
</p>


<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>
  <font size="5"> 
    <font face="century gothic, palatino, arial"> 
      Nearby Events
    </font face>
  </font size>
</h3>
<ul>
<% for location in @location.nearbys(0.8, :order => 'start_time, distance') %>
  <% if location.end_time > DateTime.now %>
    <li>
      <font size="3"> 
        <font face="century gothic, palatino, arial"> 
          <%= link_to location.event_name, location %> 
        </font face>
      </font size>
      <br> <%= location.start_time.ctime() %> - <%=location.end_time.ctime() %> 
      <br> <%=location.address%> (<%= location.distance.round(1) %> miles)
    </li>
  <% end %>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %>
  <%= link_to "View All", locations_path %>
  <%= button_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %>
  
</p>
<footer>
  <font size="3">
      (Has no official affiliation to MIT Admissions) 
  </font size>
</footer>